defaults:
  - _self_
  - callbacks: default
  - dataloader: standard
  - datasets: ???
  - loggers: test_tube
  - system: ???
  - trainer: project

cache_dir: .cache  # e.g. to save vgg weights

eval_only: false
weights_path: ~